### ISSUE TITLE
coroutine 'wait_for' was never awaited

### ISSUE THREAD

**Issue by JeffVandrewJr** [gdassori/spruned#81]
When I run spruned, I get the following, both with testnet and mainnet flags:
```
RuntimeWarning: coroutine 'wait_for' was never awaited
  asyncio.wait_for(asyncio.gather(cache.check()), timeout=30)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The logs generate however, and look normal. 

Any ideas as to what would cause that warning? Can I safely ignore it?

**Comment by gdassori** [comment]
Thanks for noticing.
It's the first run of cache agent coroutine, the flaw is the lack of the "await" instruction before the wait_for, that is used here to set a timeout.

At first sight, I thought that the check task, which enforces the cache size and cleans the stales, wasn't executed on boot. 
The consequence would be that the cache size would exceed the limits in the first 600 seconds.

Instead, the check task is just postponed of a bit, because some lines later in the code, when the check task is scheduled, is also executed for the first time. 
Supposing that the cache is already cleared the second execution should be smoothy but... I don't like that anyway. 

I'll address those flaws in the next release, but it shouldn't compromise the functionality.

**Comment by gdassori** [comment]
Behaviours changed in 6ab1f4f3e282afd11287724bfd41093fc2d39f1d. Thanks again for noticing.
